pipeline:
  identifier: Build_praveshsailor_simple_java_maven_app_1730259727336
  name: Build simple-java-maven-app
  orgIdentifier: default
  projectIdentifier: My
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: praveshsailor/simple-java-maven-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: maven build
                  spec:
                    connectorRef: Docker_Quickstart
                    image: maven:latest
                    shell: Sh
                    command: mvn cean install
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
